project:
  type: website
  output-dir: docs

website:
  title: "AP-LS Pet Blog"
  navbar:
    left:
      - href: index.qmd
        text: Gallery
      - href: pets/index.qmd
        text: View


format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

execute:
    freeze: auto

